In [ ]:
import numpy as np
import pandas as pd
from sklearn import datasets
import torch
import torch.nn as nn

In [ ]:
data = datasets.load_diabetes()

In [ ]:
X , y = data.data, data.target

In [ ]:
column = data.feature_names
column = list(set(column))
column.remove('Target')
print(column)

['s1', 's2', 'bp', 's3', 's6', 's5', 'age', 's4', 'sex', 'bmi']


In [ ]:
df = pd.DataFrame(X,columns=column)

In [ ]:
type(X)

numpy.ndarray

In [ ]:
df["n1"] = df["bp"]*df["bmi"]

In [ ]:
df

s1        s2        bp        s3        s6        s5       age  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4       sex       bmi        n1  targets  
0   -0.002592  0.019907 -0.017646 -0.001089    151.0  
1   -0.039493 -0.068332 -0.092204  0.004746     75.0  
2   -0.002592  0.002861 -0.025930 -0.001153    141.0  
3    0.034309  0.022688 -0.009362  0.000109    206.0  
4   -0.002592 -0.031988 -0.046641  0.001697    135.0  
..        ...       ...       ...       ...      ...  
437 -0.002592  0.031193  0.007207  0.000142    178.0  
438  0.034309 -0.018114  0.044485 -0.000708    104.0  
439 -0.011080 -0.046883  0.015491 -0.000246    132.0  
440  0.026560  0.044529 -0.025930 -0.001013    220.0  
441 -0.039493 -0.004222  0.003064 -0.000224     57.0  

[442 rows x 12 columns]

In [ ]:
df.drop("targets",axis=1,inplace=True)

In [ ]:
X = X.astype(np.float32)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(df,y,test_size=0.2,random_state=42)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train1= X_train1.values
X_train1 = torch.from_numpy(X_train1.astype(np.float32))
X_test1 = X_test1.values
X_test1 = torch.from_numpy(X_test1.astype(np.float32))

In [ ]:
X_test1 = torch.from_numpy(X_test1)

In [ ]:
y_train1 = torch.from_numpy(y_train1.astype(np.float32))
y_test1 = torch.from_numpy(y_test1.astype(np.float32))

In [ ]:
class mod(nn.Module):
  def __init__(self):
    super().__init__()
    self.lay1 = nn.Linear(X_train1.shape[1],32)
    self.lay2 = nn.Linear(32,1)
  def forward(self,x):
    x = self.lay1(x)
    x = self.lay2(x)
    return x

In [ ]:
type(X_train1)

torch.Tensor

In [ ]:
model1 = mod()
loss_function = nn.MSELoss()
optimizer1 = torch.optim.Adam(params = model1.parameters(), lr=0.01)

In [ ]:
epochs1 = 500
for epoch in range(epochs1):
  model1.train()
  y_hat1 = model1(X_train1)
  loss_11 = loss_function(y_hat1,y_train1)
  optimizer1.zero_grad()
  loss_11.backward()
  optimizer1.step()

  with torch.inference_mode():
    y_pred1 = model1(X_test1)
    test_loss = loss_function(y_pred1,y_test1)
    mae = nn.L1Loss()(y_pred1,y_test1)
    print(f'Epochs = {epoch}........ Training Loss = {loss_11}....... Test Loss = {test_loss}........ MAE = {mae}')

Epochs = 0........ Training Loss = 29774.21875....... Test Loss = 26581.431640625........ MAE = 145.88790893554688
Epochs = 1........ Training Loss = 29746.146484375....... Test Loss = 26555.474609375........ MAE = 145.7989044189453
Epochs = 2........ Training Loss = 29718.24609375....... Test Loss = 26529.6640625........ MAE = 145.7103729248047
Epochs = 3........ Training Loss = 29690.505859375....... Test Loss = 26503.951171875........ MAE = 145.6221160888672
Epochs = 4........ Training Loss = 29662.875....... Test Loss = 26478.26171875........ MAE = 145.53387451171875
Epochs = 5........ Training Loss = 29635.26171875....... Test Loss = 26452.51953125........ MAE = 145.44540405273438
Epochs = 6........ Training Loss = 29607.5859375....... Test Loss = 26426.626953125........ MAE = 145.3563995361328
Epochs = 7........ Training Loss = 29579.73828125....... Test Loss = 26400.46484375........ MAE = 145.26634216308594
Epochs = 8........ Training Loss = 29551.58203125....... Test Loss = 263

In [ ]:
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)

In [ ]:
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

NameError: ignored

In [ ]:
X_train.shape[1]

10

In [ ]:
class dib_ref(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer_1 = nn.Linear(X_train.shape[1],16)
    self.layer_2 = nn.Linear(16,32)
    self.layer_3 = nn.Linear(32,16)
    self.layer_4 = nn.Linear(16,1)
  def forward(self,x):
    x = self.layer_1(X_train)
    x = self.layer_2(x)
    x = self.layer_3(x)
    x = self.layer_4(x)
    return x

In [ ]:
regression_model = dib_ref()
loss_fn = nn.MSELoss()
optimizer = torch.optim.Adam(params=regression_model.parameters(),lr=0.1)

In [ ]:
epochs = 1000
for epoch in range(epochs):
  regression_model.train()
  y_hat = regression_model(X_train)
  loss = loss_fn(y_hat,y_train)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  with torch.inference_mode():
    y_pred = regression_model(X_test)
    loss2 = loss_fn(y_pred,y_test)
    mae = nn.L1Loss()(y_pred, y_test)
    print(f'Epoch = {epoch},training loss = {loss}, loss = {loss2}, MAE = {mae}')

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:536: UserWarning: Using a target size (torch.Size([353])) that is different to the input size (torch.Size([353, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:536: UserWarning: Using a target size (torch.Size([89])) that is different to the input size (torch.Size([353, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:101: UserWarning: Using a target size (torch.Size([89])) that is different to the input size (torch.Size([353, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(inp

Epoch = 0,training loss = 29794.56640625, loss = 26211.37109375, MAE = 144.61402893066406
Epoch = 1,training loss = 29355.619140625, loss = 23954.107421875, MAE = 136.5858612060547
Epoch = 2,training loss = 26970.52734375, loss = 18776.021484375, MAE = 116.06907653808594
Epoch = 3,training loss = 21465.763671875, loss = 9922.736328125, MAE = 75.19347381591797
Epoch = 4,training loss = 11840.611328125, loss = 6895.25537109375, MAE = 72.31130981445312
Epoch = 5,training loss = 7140.310546875, loss = 16117.3544921875, MAE = 109.82131958007812
Epoch = 6,training loss = 15317.169921875, loss = 7223.71533203125, MAE = 74.12931060791016
Epoch = 7,training loss = 7376.73974609375, loss = 5530.361328125, MAE = 62.28668212890625
Epoch = 8,training loss = 6604.75146484375, loss = 7406.08056640625, MAE = 65.33914947509766
Epoch = 9,training loss = 8976.2841796875, loss = 8422.671875, MAE = 68.7603988647461
Epoch = 10,training loss = 10151.888671875, loss = 7954.01220703125, MAE = 67.07658386230469

In [ ]:
type(y_hat), type(X_train), type(y_train)

(torch.Tensor, torch.Tensor, torch.Tensor)

In [ ]:
X.shape

(442, 10)

In [ ]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

SECTION **2** **bold text**

In [ ]:
import numpy as np
import pandas as pd
from sklearn import datasets
import torch
import torch.nn as nn

In [ ]:
data = datasets.load_breast_cancer()

In [ ]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
X = data.data
y = data.target

In [ ]:
X.shape

(569, 30)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
s_X = scaler.fit_transform(X)

In [ ]:
s_X

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.91202749, 0.59846245,
        0.41886396],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.63917526, 0.23358959,
        0.22287813],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.83505155, 0.40370589,
        0.21343303],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.48728522, 0.12872068,
        0.1519087 ],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.91065292, 0.49714173,
        0.45231536],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.25744136,
        0.10068215]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(s_X, y,test_size = 0.2,random_state=42)
X_train_new = torch.from_numpy(X_train.astype(np.float32))
X_test_new = torch.from_numpy(X_test.astype(np.float32))
y_train_new = torch.from_numpy(y_train.astype(np.float32))
y_test_new = torch.from_numpy(y_test.astype(np.float32))

In [ ]:
X_train_new.shape

torch.Size([455, 30])

In [ ]:
class bc_model(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer_one = nn.Linear(s_X.shape[1],16)
    self.act1 = nn.ReLU6()
    self.layer_two = nn.Linear(16,32)
    self.layer_three = nn.Linear(32,1)
    self.act2 = nn.Sigmoid()

  def forward(self,x):
    x = self.layer_one(x)
    x = self.act1(x)
    x = self.layer_two(x)
    x = self.act1(x)
    x = self.layer_three(x)
    x = self.act2(x)
    return x

In [ ]:
mod = bc_model()
error_function = nn.BCELoss()
optimizer1 = torch.optim.Adam(params=mod.parameters(),lr=0.001)

In [ ]:
epochs = 300
for epoch in range(epochs):
  mod.train()
  y_hat = mod(X_train_new)
  los = error_function(y_hat,y_train_new.unsqueeze(dim=1))
  optimizer1.zero_grad()
  los.backward()
  optimizer1.step()

  with torch.inference_mode():
    y_pred = mod(X_test_new)
    test_loss = error_function(y_pred,y_test_new.unsqueeze(dim=1))
    print(f'Epoch = {epoch},.....trainning_loss={los}.....test_loss ={test_loss}')

Epoch = 0,.....trainning_loss=0.6824575662612915.....test_loss =0.6811676025390625
Epoch = 1,.....trainning_loss=0.6809895038604736.....test_loss =0.6796764135360718
Epoch = 2,.....trainning_loss=0.6795321106910706.....test_loss =0.6781827211380005
Epoch = 3,.....trainning_loss=0.6780824065208435.....test_loss =0.6766963601112366
Epoch = 4,.....trainning_loss=0.67664635181427.....test_loss =0.675230860710144
Epoch = 5,.....trainning_loss=0.6752135157585144.....test_loss =0.6737440824508667
Epoch = 6,.....trainning_loss=0.6737599968910217.....test_loss =0.6722123622894287
Epoch = 7,.....trainning_loss=0.6722897291183472.....test_loss =0.6706504821777344
Epoch = 8,.....trainning_loss=0.6708001494407654.....test_loss =0.6690391302108765
Epoch = 9,.....trainning_loss=0.6692839860916138.....test_loss =0.6673839092254639
Epoch = 10,.....trainning_loss=0.6677375435829163.....test_loss =0.6657004952430725
Epoch = 11,.....trainning_loss=0.6661493182182312.....test_loss =0.6639774441719055
Epoch

In [ ]:
y_hat11 = mod(X_train_new)
y_hat11.shape

torch.Size([455, 2])

**SECTION THREE-3**